# Generated by Django 4.1.1 on 2022-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50)),
                ('sensor_name', models.CharField(max_length=50)),
                ('sensor_unit', models.CharField(max_length=50)),
                ('sensor_status', models.CharField(max_length=50)),
                ('sensor_location', models.CharField(max_length=500)),
                ('sensor_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpg', models.FloatField(blank=True, default=None, null=True)),
                ('smoke', models.FloatField(blank=True, default=None, null=True)),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('data_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
